In [ ]:
#если нет pip в конде, то раскомментить строку ниже
#%conda install pip
# %pip install -r requirements.txt

Импорт библиотек

In [2]:
import pandas as pd
import json
import pathlib

Извлечение путя данных

In [9]:
hack_data_path = pathlib.Path().cwd().parent/'Data'
hack_data_path

PosixPath('/home/sergey/Рабочий стол/Coding/hacathon_mlbg/Data')

Взглянем на данные

In [11]:
# тренировочные данные
train_df = pd.read_csv(hack_data_path/'train.csv')
train_df

,index,name,description,target
0,324865089,продавец кассир,<strong>Обязанности:</strong> <ul> <li>работа ...,-1
1,169467135,продавец мила (шевченко 17),<p><strong>Магазин МИЛА по адресу б-р Шевченко...,-1
2,169939030,кассир в пиццерию г витебск,"<p><strong>Устал искать работу? Может, хочешь ...",5223
3,31956044,начальник строительного участка,<p>Компании &quot;Артель-Строй&quot; на постоя...,-1
4,36781653,продавец кассир (санкт петербург бухарестская 31),<p>Обязанности:</p><p> •Обслуживание покупа...,-1
...,...,...,...,...
29995,50002587,офис менеджер,<p><strong>Обязанности:</strong></p> <ul> <li>...,3341
29996,126009334,дворник (разнорабочий),"<p>В группу компаний ООО ""Ю-МЕТ"" требуется раз...",-1
29997,183546781,офис менеджер,<strong>Обязанности:</strong> <ul> <li>прием и...,3341
29998,123274416,разнорабочий,"Производить распиловку бревен, брусьев и загот...",-1
29999,39324585,дояр,Соблюдение должностных инструкций и правил вну...,6121

In [14]:
# справочник вакансий
okz_df = pd.read_csv(hack_data_path/'okz_3_4_professions.csv', delimiter='\t')
okz_df

,code,control_number,profession,description
0,111,6.0,Руководители (представители) федеральных и рег...,Руководители\n(представители) федеральных и р...
1,1111,7.0,Руководители федеральных и региональных органо...,Руководители (представители) федеральных и ре...
2,1112,3.0,Руководители (представители) федеральных и рег...,\nРуководители (представители) федеральных и ...
3,1113,7.0,Руководители органов местного самоуправления,Руководители органов местного самоуправления ...
4,1114,0.0,Высшие должностные лица политических и обществ...,Высшие должностные лица политических\nи общес...
...,...,...,...,...
554,9621,9.0,"Посыльные, доставщики пакетов и багажа и подоб...","Посыльные, доставщики пакетов и\nбагажа и под..."
555,9622,2.0,Разнорабочие,"Разнорабочие чистят, окрашивают и\nпроводят т..."
556,9623,6.0,"Сборщики денег из торговых автоматов, контроле...","Сборщики денег из торговых автоматов, контрол..."
557,9624,8.0,Развозчики воды и сборщики дров,Развозчики воды и сборщики дров собирают воду...
558,9629,8.0,"Неквалифицированные работники, не входящие в д...",Данная начальная группа включает\nнеквалифици...

In [26]:
print(okz_df[okz_df['code']==962]['description'].to_string())

553     Другие неквалифицированные\nработники доставл...

Распакуем json файлы

In [22]:
vd1 = pd.read_json(hack_data_path/'vacancy_descriptions'/'1_parsed.json')
vd1

,ID,Position,Content
0,363107946,Секретарь,"{'Условия': ['Срочно требуется:Секретарь', 'Вы..."
1,363125198,Заместитель управляющего магазином,{'Условия': ['Наша миссия — мы делаем качество...
2,363144355,Персональный менеджер,"{'Требования': ['окончили вуз', 'разбираетесь ..."
3,363340232,Продавец-консультант ECCO (ТЦ Сити Молл),{'Требования': ['Обладаешь хорошими коммуникат...
4,363383054,Агент/Риэлтор (Помощник Риэлтора),{'Обязанности': ['Организовывать и проводить п...
...,...,...,...
9996,27051209,Старший специалист отдела продаж,"{'Требования': ['Высшее образование', 'Опыт ра..."
9997,27059696,Сортировщик/Сортировщица,{'Требования': ['Опыт работы на складах желате...
9998,27062110,Водитель-курьер,{'Обязанности': ['Курьерская компания производ...
9999,27071513,Начальник отдела,"{'Обязанности': ['обеспечивает установку, прав..."
10000,27092509,Машинист экскаватора (в п. Чегдомын Хабаровско...,{'Условия': ['оформление в соответствии с треб...